INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (1, N'mickey123 ', N'password123', N'mickey@example.com', N'Mickey Mouse')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (2, N'cinderella456', N'password456', N'cinderella@example.com', N'Cinderella')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (3, N'aurora789', N'password789', N'aurora@example.com', N'Aurora')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (4, N'ariel101', N'password101', N'ariel@example.com', N'Ariel')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (5, N'belle202', N'password202', N'belle@example.com', N'Belle')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (6, N'jasmine303', N'password303', N'jasmine@example.com', N'Jasmine')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (7, N'pocahontas404', N'password404', N'pocahontas@example.com', N'Pocahontas')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (8, N'princecharming123', N'password123', N'princecharming@example.com', N'Prince Charming')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (9, N'princephillip456', N'password456', N'princephillip@example.com', N'Prince Phillip')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (10, N'princeeric789', N'password789', N'princeeric@example.com', N'Prince Eric')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (11, N'beast101', N'password101', N'beast@example.com', N'Beast')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (12, N'aladdin202', N'password202', N'aladdin@example.com', N'Aladdin')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (13, N'johnsmith303', N'password303', N'johnsmith@example.com', N'John Smith')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (14, N'lishang404', N'password404', N'lishang@example.com', N'Li Shang')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (15, N'naveen505', N'password505', N'naveen@example.com', N'Naveen')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (16, N'shrek123', N'password123', N'shrek@example.com', N'Shrek')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (17, N'fiona456', N'password456', N'fiona@example.com', N'Fiona')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (18, N'donkey789', N'password789', N'donkey@example.com', N'Donkey')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (19, N'farquaad101', N'password101', N'farquaad@example.com', N'Farquaad')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (20, N'dragon202', N'password202', N'dragon@example.com', N'Dragon')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (21, N'gingy303', N'password303', N'gingy@example.com', N'Gingy')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (22, N'pinocchio404', N'password404', N'pinocchio@example.com', N'Pinocchio')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (23, N'ursula123', N'password123', N'ursula@example.com', N'Ursula')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (24, N'maleficent456', N'password456', N'maleficent@example.com', N'Maleficent')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (25, N'jafar789', N'password789', N'jafar@example.com', N'Jafar')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (26, N'scar101', N'password101', N'scar@example.com', N'Scar')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (27, N'cruella202', N'password202', N'cruella@example.com', N'Cruella')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (28, N'gaston303', N'password303', N'gaston@example.com', N'Gaston')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (29, N'hook404', N'password404', N'hook@example.com', N'Captain Hook')
INSERT INTO [dbo].[userAccounts] ([userId], [userName], [userPassword], [userEmail], [fullName]) VALUES (30, N'hades505', N'password505', N'hades@example.com', N'Hades')
